name: Lint and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.lts }}
    steps:
    - name: Select all current LTS versions of Node.js
      id: generate-matrix
      uses: msimerson/node-lts-versions@v1

  lint-and-build:
    runs-on: macos-latest
    needs:
    - prepare_matrix
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.prepare_matrix.outputs.versions) }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build
